apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: goud-deployment
  namespace: goud
spec:
  selector:
    matchLabels:
      app: goud
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: goud
    spec:
      containers:
      - name: goud
        image: 349948765351.dkr.ecr.ap-south-1.amazonaws.com/goudcloud:latest
        ports:
        - containerPort: 80
